server:
  port: 8084
  tomcat:
    accesslog:
      enabled: true
      directory: /
      prefix: access
      buffered: false
      suffix: .log
      file-date-format: .yyyy-MM-dd
      pattern: common
      rotate: true
      rename-on-rotate: true
    basedir: logs/

spring:
  application:
    name: Search Engine
  datasource:
    username: root
    password: skillbox
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        #format_sql: true
    hibernate:
      ddl-auto: update
    #show-sql: true

logging:
  file:
    name: logs/search-engine.log
  charset:
    file: UTF-8
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql:
#              BasicBinder: trace

settings:
  user-agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0
  referrer: https://www.google.com
  messages:
    indexing_start: Запущено индексирование
    indexing_processing: Обработка адреса
    indexing_complete: Индексирование завершено
    indexing_interrupt: Прервали индексирование
    indexing_launched: Индексация уже запущена
    indexing_not_launched: Индексация не запущена
    indexing_unknown_url: Адрес не найден
    indexing_unexpected_error: Неожиданная ошибка
    indexing_stopped_by_user: Индексация остановлена пользователем
    indexing_url_parse_error: Ошибка разбора ссылок на странице
    indexing_read_timeout_error: Веб-сайт не ответил за отведенное время
    indexing_wrong_content_type: Не правильный тип контента
    url_empty: Адрес страницы не передан
    url_out_of_range: Данная страница находится за пределами сайтов, указанных в конфигурационном файле
    search_query_empty: Запрос для поиска не задан
    search_site_not_found: Переданный адрес веб-сайта не найден
    search_site_bad_url: Неверный формат адреса веб-сайта
    search_unexpected_error: Во время поиска произошла неожиданная ошибка
    search_number_positive: Значение поля %s должно быть положительным целым числом, большим либо равным нулю
    search_unknown_message_key: Неизвестный ключ сообщения об ошибке
    search_message_key_not_set: Поле %s, ключ сообщения об ошибке не задан
  sites:
    - url: https://skillbox.ru/
      name: Skillbox
    - url: https://www.playback.ru/
      name: PlayBack.Ru
    - url: https://dombulgakova.ru/
      name: Булгаковский дом
    - url: https://1001sekret.ru/
      name: 1001 Секрет – Полезные советы и важные секреты
    - url: http://ugorau.ru/
      name: Угораю.ру — Самые угарные приколы сети!
    - url: https://sekreti-domovodstva.ru/
      name: Секреты домоводства
    - url: https://camcebekulinar.ru/
      name: Сам себе кулинар
    - url: https://silaznaniya8.ru/
      name: Сила знания
    - url: https://vkusnogotovlu.ru/
      name: Вкусно готовлю
    - url: http://cimus.biz/
      name: Цимус
    - url: https://www.svetlovka.ru/
      name: Центральная городская молодежная библиотека им. М. А. Светлова
    - url: https://www.dextra.ru/
      name: Интернет-агентство Dextra
